name = "Tempus"
uuid = "e6262be2-5787-4bdc-bc3f-4b5a3442fa30"
version = "1.0.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
Dates = "1.11.0"
Logging = "1.11.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
