name = "Tempus"
uuid = "e6262be2-5787-4bdc-bc3f-4b5a3442fa30"
version = "2.0.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[weakdeps]
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[extensions]
TempusSQLiteExt = "SQLite"

[compat]
JSON = "1"
SQLite = "1"
TimeZones = "1"
julia = "1.9"

[extras]
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[targets]
test = ["Test", "TimeZones", "SQLite"]
