name = "Tempus"
uuid = "e6262be2-5787-4bdc-bc3f-4b5a3442fa30"
version = "1.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[weakdeps]
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[extensions]
TempusSQLiteExt = "SQLite"

[compat]
julia = "1.9"

[extras]
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
